CREATE
(P1:Person {id: 1, identity:"#1 Chiniese Woman"}),
(P2:Person {id:2, identity:"#2 Tour Guide"}),
(P3:Person {id:3, identity:"#3 Friend of Tour Guide"}),
(P4:Person {id:4, identity:"#4"}),
(P5:Person {id:5, identity:"#5"}),
(P6:Person {id:6, identity:"#6"}),
(P7:Person {id:7, identity:"#7"}),
(P8:Person {id:8, identity:"#8"}),
(P9:Person {id:9, identity:"#9"}),
(P10:Person {id:10, identity:"#10"}),
(P11:Person {id:11, identity:"#11"}),
(P12:Person {id:12, identity:"#12"}),
(P13:Person {id:13, identity:"#13"}),
(P14:Person {id:14, identity:"#14"}),
(P15:Person {id:15, identity:"#15"}),

(Q1:QuarintineCenter{ place:"Kandakadu"}),
(Q2:QuarintineCenter{ place:"Galkanda"}),

(P2)-[:Infected]->(P3),
(P4)-[:Infected]->(P12),
(P3)-[:Infected]->(P11),

(C1:Country {id: 1, name:"China"}),
(C2:Country {id: 2, name:"Italy"}),
(C3:Country {id: 3, name:"Sri Lanka"}),
(C4:Country {id: 3, name:"Gernamy"}),

(P1)-[:From]->(C1),
(P4)-[:From]->(C4),
(P5)-[:From]->(C2),
(P6)-[:From]->(C2),
(P7)-[:From]->(C2),
(P8)-[:From]->(C2),
(P9)-[:From]->(C2),
(P10)-[:From]->(C2),
(P11)-[:From]->(C3),
(P12)-[:From]->(C4),
(P13)-[:From]->(C2),
(P14)-[:From]->(C2),
(P15)-[:From]->(C2),

(P6)-[:Quarintined]->(Q1),
(P7)-[:Quarintined]->(Q1),
(P9)-[:Quarintined]->(Q1),
(P5)-[:Quarintined]->(Q1),
(P13)-[:Quarintined]->(Q2)
